# Generated by Django 5.2.5 on 2025-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7),
        ),
        migrations.AddField(
            model_name='location',
            name='emoji',
            field=models.CharField(default='📍', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='emoji',
            field=models.CharField(default='🏷️', max_length=10),
        ),
    ]
