# Generated by Django 5.2.5 on 2025-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_color_location_emoji_tag_color_tag_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_tag_color', models.CharField(default='#6b7280', help_text='Default color for new tags (hex format)', max_length=7)),
                ('default_tag_emoji', models.CharField(default='🏷️', help_text='Default emoji for new tags', max_length=10)),
                ('default_location_color', models.CharField(default='#6b7280', help_text='Default color for new locations (hex format)', max_length=7)),
                ('default_location_emoji', models.CharField(default='📍', help_text='Default emoji for new locations', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
